name: STAGE Trigger Webhook

on:
  push:
    branches:
      - develop  # Change this to your desired branch
  workflow_dispatch:

jobs:
  call_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Call Webhook
        run: curl -X POST ${{ vars.STAGE_WEBHOOK_URL }}
